In [5]:
import pandas as pd
df = pd.read_csv(r"C:\Users\cano9\Downloads\aldia_operaciones_Q1_2026.csv")
print(df.shape)          # debe mostrar (41967, 22)
print(df['regional'].value_counts())
df.head(100)

(41967, 23)
regional
Bucaramanga Zona Metro Urbano    22882
Regional Cucuta                  11949
Regional Barrancabermeja          2232
Regional Sur                      1936
Regional Ocaña - Aguachica        1639
Regional Reexpedición             1329
Name: count, dtype: int64

,remesa_id,fecha,año,trimestre,mes,mes_num,semana_año,dia_semana,regional,tipo_operacion,...,vehiculo,tipo_mercancia,peso_kg,unidades,hora_salida_plataforma,hora_entrega,tiempo_gestion_min,estado_entrega,entregado,novedad
0,REM-000001,2026-01-02,2026,Q1,January,1,1,Friday,Bucaramanga Zona Metro Urbano,Urbano,...,Furgón pequeño,Productos de aseo,18.0,3,05:48,07:46,118,Entregado con novedad,1,Firma ilegible
1,REM-000002,2026-01-02,2026,Q1,January,1,1,Friday,Bucaramanga Zona Metro Urbano,Urbano,...,Camioneta NHR,Electrodomésticos pequeños,18.0,4,05:24,06:07,27,Entregado,1,NaN
2,REM-000003,2026-01-02,2026,Q1,January,1,1,Friday,Bucaramanga Zona Metro Urbano,Urbano,...,Moto NKD,Repuestos automotriz,18.0,6,05:35,06:59,52,Reprogramado,0,NaN
3,REM-000004,2026-01-02,2026,Q1,January,1,1,Friday,Bucaramanga Zona Metro Urbano,Urbano,...,Moto NKD,Paquetería e-commerce,18.0,5,05:54,07:02,44,Devuelto a plataforma,0,Rechazado por cliente
4,REM-000005,2026-01-02,2026,Q1,January,1,1,Friday,Bucaramanga Zona Metro Urbano,Urbano,...,Camioneta NHR,Electrodomésticos pequeños,18.0,5,05:38,07:54,96,Entregado,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,REM-000096,2026-01-02,2026,Q1,January,1,1,Friday,Bucaramanga Zona Metro Urbano,Urbano,...,Camioneta NHR,Electrodomésticos pequeños,18.0,3,07:47,21:25,58,Entregado,1,NaN
96,REM-000097,2026-01-02,2026,Q1,January,1,1,Friday,Bucaramanga Zona Metro Urbano,Urbano,...,Moto XR,Productos de aseo,18.0,2,07:05,12:13,116,Devuelto a plataforma,0,No reclamado en 48h
97,REM-000098,2026-01-02,2026,Q1,January,1,1,Friday,Bucaramanga Zona Metro Urbano,Urbano,...,Moto NKD,Repuestos automotriz,18.0,3,08:52,12:20,96,Entregado,1,NaN
98,REM-000099,2026-01-02,2026,Q1,January,1,1,Friday,Bucaramanga Zona Metro Urbano,Urbano,...,Furgón pequeño,Paquetería e-commerce,18.0,3,06:41,14:06,23,No entregado - dirección errónea,0,Sin número interior
99,REM-000100,2026-01-02,2026,Q1,January,1,1,Friday,Bucaramanga Zona Metro Urbano,Urbano,...,Moto NKD,Electrodomésticos pequeños,18.0,4,08:07,04:22,27,Entregado,1,NaN

In [6]:
import pandas as pd
import numpy as np

# Cargar dataset
df = pd.read_csv(r"C:\Users\cano9\Downloads\aldia_operaciones_Q1_2026.csv")

# Primer vistazo
print(f"Filas: {df.shape[0]:,}  |  Columnas: {df.shape[1]}")
print("\nTipos de datos:")
print(df.dtypes)
print("\nPrimeras 3 filas:")
df.head(3)

Filas: 41,967  |  Columnas: 23

Tipos de datos:
remesa_id                  object
fecha                      object
año                         int64
trimestre                  object
mes                        object
mes_num                     int64
semana_año                  int64
dia_semana                 object
regional                   object
tipo_operacion             object
conductor_id               object
conductor_nombre           object
zona_entrega               object
vehiculo                   object
tipo_mercancia             object
peso_kg                   float64
unidades                    int64
hora_salida_plataforma     object
hora_entrega               object
tiempo_gestion_min          int64
estado_entrega             object
entregado                   int64
novedad                    object
dtype: object

Primeras 3 filas:

,remesa_id,fecha,año,trimestre,mes,mes_num,semana_año,dia_semana,regional,tipo_operacion,...,vehiculo,tipo_mercancia,peso_kg,unidades,hora_salida_plataforma,hora_entrega,tiempo_gestion_min,estado_entrega,entregado,novedad
0,REM-000001,2026-01-02,2026,Q1,January,1,1,Friday,Bucaramanga Zona Metro Urbano,Urbano,...,Furgón pequeño,Productos de aseo,18.0,3,05:48,07:46,118,Entregado con novedad,1,Firma ilegible
1,REM-000002,2026-01-02,2026,Q1,January,1,1,Friday,Bucaramanga Zona Metro Urbano,Urbano,...,Camioneta NHR,Electrodomésticos pequeños,18.0,4,05:24,06:07,27,Entregado,1,NaN
2,REM-000003,2026-01-02,2026,Q1,January,1,1,Friday,Bucaramanga Zona Metro Urbano,Urbano,...,Moto NKD,Repuestos automotriz,18.0,6,05:35,06:59,52,Reprogramado,0,NaN

In [7]:
df = df.rename(columns={
    "remesa_id":                "ID_Remesa",
    "fecha":                    "Fecha",
    "año":                      "Año",
    "trimestre":                "Trimestre",
    "mes":                      "Mes",
    "mes_num":                  "Mes_Numero",
    "semana_año":               "Semana",
    "dia_semana":               "Dia_Semana",
    "regional":                 "Regional",
    "tipo_operacion":           "Tipo_Operacion",
    "conductor_id":             "ID_Conductor",
    "conductor_nombre":         "Conductor",
    "zona_entrega":             "Zona_Entrega",
    "vehiculo":                 "Vehiculo",
    "tipo_mercancia":           "Tipo_Mercancia",
    "peso_kg":                  "Peso_KG",
    "unidades":                 "Unidades",
    "hora_salida_plataforma":   "Hora_Salida",
    "hora_entrega":             "Hora_Entrega",
    "tiempo_gestion_min":       "Tiempo_Gestion_Min",
    "estado_entrega":           "Estado_Entrega",
    "entregado":                "Entregado",
    "novedad":                  "Novedad"
})

print("Columnas renombradas:")
print(df.columns.tolist())

Columnas renombradas:
['ID_Remesa', 'Fecha', 'Año', 'Trimestre', 'Mes', 'Mes_Numero', 'Semana', 'Dia_Semana', 'Regional', 'Tipo_Operacion', 'ID_Conductor', 'Conductor', 'Zona_Entrega', 'Vehiculo', 'Tipo_Mercancia', 'Peso_KG', 'Unidades', 'Hora_Salida', 'Hora_Entrega', 'Tiempo_Gestion_Min', 'Estado_Entrega', 'Entregado', 'Novedad']

In [8]:
dias_es = {
    "Monday":"Lunes", "Tuesday":"Martes", "Wednesday":"Miércoles",
    "Thursday":"Jueves", "Friday":"Viernes", "Saturday":"Sábado", "Sunday":"Domingo"
}
meses_es = {
    "January":"Enero", "February":"Febrero", "March":"Marzo",
    "April":"Abril", "May":"Mayo", "June":"Junio",
    "July":"Julio", "August":"Agosto", "September":"Septiembre",
    "October":"Octubre", "November":"Noviembre", "December":"Diciembre"
}

df["Dia_Semana"] = df["Dia_Semana"].map(dias_es)
df["Mes"]        = df["Mes"].map(meses_es)

print("Días únicos:", df["Dia_Semana"].unique())
print("Meses únicos:", df["Mes"].unique())

Días únicos: ['Viernes' 'Sábado' 'Lunes' 'Martes' 'Miércoles' 'Jueves']
Meses únicos: ['Enero' 'Febrero' 'Marzo' 'Abril']

In [9]:
# Fecha como tipo fecha (no texto)
df["Fecha"] = pd.to_datetime(df["Fecha"])

# Columna: ¿fue entregado exitosamente? (Sí / No)
df["Entrega_Exitosa"] = df["Entregado"].map({1: "Sí", 0: "No"})

# Columna: categoría de peso
def categorizar_peso(kg):
    if kg < 5:       return "Liviano (<5 kg)"
    elif kg < 50:    return "Mediano (5-50 kg)"
    elif kg < 200:   return "Pesado (50-200 kg)"
    else:            return "Carga masiva (>200 kg)"

df["Categoria_Peso"] = df["Peso_KG"].apply(categorizar_peso)

# Columna: categoría de tiempo de gestión
def cat_tiempo(min):
    if min <= 30:    return "Rápido (≤30 min)"
    elif min <= 90:  return "Normal (31-90 min)"
    elif min <= 180: return "Demorado (91-180 min)"
    else:            return "Crítico (>180 min)"

df["Categoria_Tiempo"] = df["Tiempo_Gestion_Min"].apply(cat_tiempo)

print("Nuevas columnas creadas:")
print(df[["Entrega_Exitosa","Categoria_Peso","Categoria_Tiempo"]].value_counts().head(10))

Nuevas columnas creadas:
Entrega_Exitosa  Categoria_Peso      Categoria_Tiempo
Sí               Mediano (5-50 kg)   Normal (31-90 min)       7816
No               Mediano (5-50 kg)   Normal (31-90 min)       5174
Sí               Pesado (50-200 kg)  Crítico (>180 min)       5068
                                     Demorado (91-180 min)    4615
                 Mediano (5-50 kg)   Demorado (91-180 min)    4078
                 Pesado (50-200 kg)  Normal (31-90 min)       3036
No               Mediano (5-50 kg)   Demorado (91-180 min)    2717
                 Pesado (50-200 kg)  Crítico (>180 min)       2097
Sí               Mediano (5-50 kg)   Rápido (≤30 min)         2080
No               Pesado (50-200 kg)  Demorado (91-180 min)    1922
Name: count, dtype: int64

In [10]:
print("Valores nulos por columna:")
print(df.isnull().sum())

# La columna Novedad tiene nulos válidos (remesas sin novedad = cadena vacía)
df["Novedad"] = df["Novedad"].fillna("Sin novedad")

print("\n¿Duplicados?", df.duplicated().sum())
print("\nDataset limpio listo. Forma final:", df.shape)

Valores nulos por columna:
ID_Remesa                 0
Fecha                     0
Año                       0
Trimestre                 0
Mes                       0
Mes_Numero                0
Semana                    0
Dia_Semana                0
Regional                  0
Tipo_Operacion            0
ID_Conductor              0
Conductor                 0
Zona_Entrega              0
Vehiculo                  0
Tipo_Mercancia            0
Peso_KG                   0
Unidades                  0
Hora_Salida               0
Hora_Entrega              0
Tiempo_Gestion_Min        0
Estado_Entrega            0
Entregado                 0
Novedad               28834
Entrega_Exitosa           0
Categoria_Peso            0
Categoria_Tiempo          0
dtype: int64

¿Duplicados? 0

Dataset limpio listo. Forma final: (41967, 26)

In [11]:
df.to_csv("aldia_Q1_2026_limpio.csv", index=False, encoding="utf-8-sig")
print("✅ Archivo exportado: aldia_Q1_2026_limpio.csv")
print(f"   {df.shape[0]:,} filas  |  {df.shape[1]} columnas")

✅ Archivo exportado: aldia_Q1_2026_limpio.csv
   41,967 filas  |  26 columnas